name: hospital_app
description: test app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.2

  #network
  dio: ^5.3.4

  #rx
  rxdart: ^0.27.7

  #database
  drift: ^2.13.0
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

  #svg
  flutter_svg: ^2.0.9

  #bloc
  bloc: ^8.0.0
  flutter_bloc: ^8.1.3

  #utils
  intl: ^0.18.1

  #loading indicator
  loading_indicator: ^3.1.1


  #navigation
  go_router: ^12.1.1


  #service locator
  get_it: ^7.6.4


  #annotations and extensions
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  drift_dev: ^2.13.0
  json_serializable: ^6.7.1
  freezed: ^2.3.2



flutter:

  uses-material-design: true

  assets:
    - assets/images/arrow_l.svg
    - assets/images/arrow_r.svg
    - assets/images/hospital_icon.svg
    - assets/images/i_icon.svg
    - assets/images/imp_icon.svg
    - assets/images/layers_icon.svg
    - assets/images/active_layers_icon.svg
    - assets/images/profile_icon.svg
    - assets/images/schedule_icon.svg
    - assets/images/error_icon.png
    - assets/images/success_icon.png
    - assets/images/active_hospital_icon.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
